global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: 'spring-actuator'
    authorization:
      credentials: 'abc'
      type: Bearer
    metrics_path: '/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'icblog-backend:8080' ]